<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CastCrewTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cast_crew')->delete();
        
        \DB::table('cast_crew')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Michael Johnson',
                'file_url' => 'michael_johnson.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Versatile actor known for his dynamic roles in action and drama films. 🎬',
                'place_of_birth' => 'New York, USA',
                'dob' => '1985-04-13',
                'designation' => 'Main Actor',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:09',
                'updated_at' => '2024-10-22 09:20:09',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'James Williams',
                'file_url' => 'james_williams.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Acclaimed actor with a knack for bringing complex characters to life. 🎭',
                'place_of_birth' => 'Los Angeles, USA',
                'dob' => '1980-04-14',
                'designation' => 'Main Actor',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:09',
                'updated_at' => '2024-10-22 09:20:09',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Robert Brown',
                'file_url' => 'robert_brown.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Renowned actor famed for his powerful performances in thrillers. 🔪',
                'place_of_birth' => 'Chicago, USA',
                'dob' => '1990-02-07',
                'designation' => 'Actor',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:09',
                'updated_at' => '2024-10-22 09:20:09',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'David Jones',
                'file_url' => 'david_jones.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Award-winning actor known for his captivating roles in historical dramas. 📜',
                'place_of_birth' => 'London, UK',
                'dob' => '1985-08-04',
                'designation' => 'Actor',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:09',
                'updated_at' => '2024-10-22 09:20:09',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'John Miller',
                'file_url' => 'john_miller.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Charismatic actor celebrated for his comedic timing and charm. 😂',
                'place_of_birth' => 'Toronto, Canada',
                'dob' => '1982-12-09',
                'designation' => 'Actor',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:09',
                'updated_at' => '2024-10-22 09:20:09',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Daniel Anderson',
                'file_url' => 'daniel_anderson.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Talented actor known for his intense and compelling performances in horror films. 👻',
                'place_of_birth' => 'Sydney, Australia',
                'dob' => '1990-09-07',
                'designation' => 'Voice Actor',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:09',
                'updated_at' => '2024-10-22 09:20:09',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Matthew Clark',
                'file_url' => 'matthew_clark.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Dynamic actor recognized for his roles in inspirational and motivational films. 🌟',
                'place_of_birth' => 'Dublin, Ireland',
                'dob' => '1980-01-10',
                'designation' => 'Voice Actor',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:09',
                'updated_at' => '2024-10-22 09:20:09',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Andrew Martinez',
                'file_url' => 'andrew_martinez.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Acclaimed actor with a strong presence in romantic films. 💖',
                'place_of_birth' => 'Madrid, Spain',
                'dob' => '1986-01-23',
                'designation' => 'Actor',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:09',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Joshua Rodriguez',
                'file_url' => 'joshua_rodriguez.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Renowned for his action-packed roles and high-energy performances. 💥',
                'place_of_birth' => 'Mexico City, Mexico',
                'dob' => '1985-07-19',
                'designation' => 'Actor',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Christopher Lopez',
                'file_url' => 'christopher_lopez.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Versatile actor known for his roles in both comedy and drama. 🎭',
                'place_of_birth' => 'Buenos Aires, Argentina',
                'dob' => '1991-06-13',
                'designation' => 'Main Actor',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Emily Johnson',
                'file_url' => 'emily_johnson.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Talented actress known for her captivating performances in dramas. 🎬',
                'place_of_birth' => 'New York, USA',
                'dob' => '1993-01-05',
                'designation' => 'Main Actress',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Laura Turner',
                'file_url' => 'laura_turner.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Renowned actress with a flair for bringing historical characters to life. 📜',
                'place_of_birth' => 'Los Angeles, USA',
                'dob' => '1990-08-18',
                'designation' => 'Main Actress',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Olivia Martinez',
                'file_url' => 'olivia_martinez.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Acclaimed actress known for her dynamic roles in romantic films. 💖',
                'place_of_birth' => 'Madrid, Spain',
                'dob' => '1992-03-10',
                'designation' => 'Actress',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Isabella Brown',
                'file_url' => 'isabella_brown.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Versatile actress with a talent for both comedy and drama. 😂',
                'place_of_birth' => 'London, UK',
                'dob' => '1995-06-08',
                'designation' => 'Actress',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Lily Clark',
                'file_url' => 'lily_clark.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Celebrated actress known for her intense performances in thrillers. 🔪',
                'place_of_birth' => 'Toronto, Canada',
                'dob' => '1997-05-06',
                'designation' => 'Voice Actress',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Charlotte Garcia',
                'file_url' => 'charlotte_garcia.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Acclaimed actress renowned for her roles in horror films. 👻',
                'place_of_birth' => 'Sydney, Australia',
                'dob' => '1991-02-05',
                'designation' => 'Voice Actress',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Amelia Martinez',
                'file_url' => 'amelia_martinez.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Dynamic actress recognized for her roles in inspirational movies. 🌟',
                'place_of_birth' => 'Mexico City, Mexico',
                'dob' => '1994-07-21',
                'designation' => 'Actress',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Jessica Adams',
                'file_url' => 'jessica_adams.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Talented actress known for her compelling performances in action films. 💥',
                'place_of_birth' => 'Dublin, Ireland',
                'dob' => '1992-08-15',
                'designation' => 'Actress',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Megan Collins',
                'file_url' => 'megan_collins.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Versatile actress known for her roles in both romantic and drama films. 💖',
                'place_of_birth' => 'Seoul, South Korea',
                'dob' => '1988-03-08',
                'designation' => 'Actress',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Grace Taylor',
                'file_url' => 'grace_taylor.png',
                'type' => 'actor',
                'tmdb_id' => NULL,
                'bio' => 'Acclaimed actress celebrated for her performances in historical dramas. 📜',
                'place_of_birth' => 'Cape Town, South Africa',
                'dob' => '1989-02-11',
                'designation' => 'Actress',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Thomas Smith',
                'file_url' => 'thomas_smith.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Visionary director known for his innovative storytelling and cinematic techniques. 🎬',
                'place_of_birth' => 'New York, USA',
                'dob' => '1985-04-13',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'William Johnson',
                'file_url' => 'william_johnson.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Acclaimed director with a flair for intense action sequences. 💥',
                'place_of_birth' => 'Los Angeles, USA',
                'dob' => '1980-04-14',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Henry Taylor',
                'file_url' => 'henry_taylor.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Renowned director known for his compelling historical dramas. 📜',
                'place_of_birth' => 'Chicago, USA',
                'dob' => '1990-02-07',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Charles Wilson',
                'file_url' => 'charles_wilson.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Award-winning director famous for his work in horror films. 👻',
                'place_of_birth' => 'London, UK',
                'dob' => '1985-08-04',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'George Harris',
                'file_url' => 'george_harris.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Innovative director known for his unique approach to comedy. 😂',
                'place_of_birth' => 'Toronto, Canada',
                'dob' => '1982-12-09',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Anthony Clark',
                'file_url' => 'anthony_clark.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Talented director celebrated for his inspirational and motivational films. 🌟',
                'place_of_birth' => 'Sydney, Australia',
                'dob' => '1980-04-18',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Edward Lewis',
                'file_url' => 'edward_lewis.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Dynamic director recognized for his work in romantic films. 💖',
                'place_of_birth' => 'Dublin, Ireland',
                'dob' => '1982-01-11',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Daniel Walker',
                'file_url' => 'daniel_walker.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Acclaimed director known for his thrilling and suspenseful films. 🔪',
                'place_of_birth' => 'Madrid, Spain',
                'dob' => '1981-05-12',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Matthew Collins',
                'file_url' => 'matthew_collins.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Renowned for his action-packed films and high-energy direction. 🎥',
                'place_of_birth' => 'Mexico City, Mexico',
                'dob' => '1983-02-18',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Richard King',
                'file_url' => 'richard_king.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Celebrated director known for his masterful storytelling in drama. 🎭',
                'place_of_birth' => 'Buenos Aires, Argentina',
                'dob' => '1987-03-27',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Sophia Williams',
                'file_url' => 'sophia_williams.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Acclaimed director known for her profound and emotional storytelling. 🎬',
                'place_of_birth' => 'New York, USA',
                'dob' => '1989-06-15',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Emma Thompson',
                'file_url' => 'emma_thompson.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Visionary director celebrated for her work in romantic films. 💖',
                'place_of_birth' => 'Los Angeles, USA',
                'dob' => '1990-08-16',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Abigail Thompson',
                'file_url' => 'abigail_thompson.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Renowned director known for her historical dramas and biopics. 📜',
                'place_of_birth' => 'Madrid, Spain',
                'dob' => '1992-06-21',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Natalie Parker',
                'file_url' => 'natalie_parker.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Award-winning director famous for her suspenseful thrillers. 🔪',
                'place_of_birth' => 'London, UK',
                'dob' => '1991-07-25',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Mili Davis',
                'file_url' => 'mili_davis.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Talented director known for her innovative approach to comedy. 😂',
                'place_of_birth' => 'Toronto, Canada',
                'dob' => '1988-08-10',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Chloe Mitchell',
                'file_url' => 'chloe_mitchell.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Dynamic director recognized for her powerful horror films. 👻',
                'place_of_birth' => 'Sydney, Australia',
                'dob' => '1989-12-25',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Sarah Foster',
                'file_url' => 'sarah_foster.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Acclaimed director known for her inspirational and motivational films. 🌟',
                'place_of_birth' => 'Mexico City, Mexico',
                'dob' => '1987-08-24',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Victoria Evans',
                'file_url' => 'victoria_evans.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Visionary director celebrated for her thrilling and suspenseful films. 🔪',
                'place_of_birth' => 'London, UK',
                'dob' => '1986-11-27',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Ava Brown',
                'file_url' => 'ava_brown.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Renowned for her action-packed and high-energy films. 💥',
                'place_of_birth' => 'Toronto, Canada',
                'dob' => '1988-09-06',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Sophia Lee',
                'file_url' => 'sophia_lee.png',
                'type' => 'director',
                'tmdb_id' => NULL,
                'bio' => 'Celebrated director known for her compelling drama films. 🎭',
                'place_of_birth' => 'Sydney, Australia',
                'dob' => '1991-08-30',
                'designation' => 'Director',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 09:20:10',
                'updated_at' => '2024-10-22 09:20:10',
            ),
        ));
        
        
    }
}