<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LiveTvChannelTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('live_tv_channel')->delete();
        
        \DB::table('live_tv_channel')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Aaj Kal LIVE TV',
                'poster_url' => 'aaj_kal_live_tv.png',
                'category_id' => 1,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Stay informed with live news broadcasts and in-depth analysis on Aaj Kal LIVE TV. Never miss a moment of the latest updates from around the world.',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'ABP Sports',
                'poster_url' => 'abp_sports.png',
                'category_id' => 2,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 1,
                'description' => 'Catch all the live sports action on ABP Sports, covering your favorite games and tournaments with expert commentary and thrilling highlights.',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'DN TV',
                'poster_url' => 'dn_tv.png',
                'category_id' => 3,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 2,
                'description' => 'Enjoy a variety of entertainment shows on DN TV, featuring reality TV, talent competitions, talk shows, and award ceremonies.',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => '9xm',
                'poster_url' => '9xm.png',
                'category_id' => 4,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 3,
                'description' => 'Music & Concerts channel featuring live performances and more.',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'BBP',
                'poster_url' => 'bbp.png',
                'category_id' => 5,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 4,
                'description' => 'Educational & Documentary channel with a wide range of informative content.',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'M TV',
                'poster_url' => 'm_tv.png',
                'category_id' => 4,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Free Music & Concerts channel with live performances and more.',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'ZNews 24/7',
                'poster_url' => 'znews_247.png',
                'category_id' => 1,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Round-the-clock coverage of global news and current events to keep you informed all day. 🌍🕓',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Sports Max',
                'poster_url' => 'sports_max.png',
                'category_id' => 2,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 1,
                'description' => 'The ultimate channel for live sports events, from football to cricket, with non-stop action. 🏆📢',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Vibe TV',
                'poster_url' => 'vibe_tv.png',
                'category_id' => 3,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 2,
                'description' => 'The hottest variety of live entertainment, from reality shows to talk shows and much more. 🎭🔥',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Beat Box',
                'poster_url' => 'beat_box.png',
                'category_id' => 4,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Feel the beat with live music performances, DJ sets, and non-stop tunes. 🎧🎵',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Brain TV',
                'poster_url' => 'brain_tv.png',
                'category_id' => 5,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 4,
                'description' => 'Dive into a world of learning with live educational shows and insightful documentaries. 🧠📺',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Khabar NOW',
                'poster_url' => 'khabar_now.png',
                'category_id' => 1,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 2,
                'description' => 'Instant access to real-time news and headlines that matter most, bringing the world to your screen. 📰📢',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Goal TV',
                'poster_url' => 'goal_tv.png',
                'category_id' => 2,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Your destination for all things football, with live coverage of matches, interviews, and goals. ⚽🎥',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Star Bliss',
                'poster_url' => 'star_bliss.png',
                'category_id' => 3,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Bringing you a star-studded lineup of live entertainment, talk shows, and celebrity interviews. ⭐🎬',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Groove LIVE',
                'poster_url' => 'groove_live.png',
                'category_id' => 4,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Get into the groove with live music shows, concerts, and your favorite artists. 🎼🎸',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Docu Vision',
                'poster_url' => 'docu_vision.png',
                'category_id' => 5,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 4,
                'description' => 'Explore fascinating live documentaries on a range of topics, from history to science. 📚🎬',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Vision TV',
                'poster_url' => 'vision_tv.png',
                'category_id' => 1,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Sharp and focused news, providing clear insights into the events shaping the world today. 🔍📺',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Win Sports',
                'poster_url' => 'win_sports.png',
                'category_id' => 2,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 1,
                'description' => 'Bringing the winning moments from the biggest sporting events, straight to your screen, live. 🎖️📺',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Buzz LIVE',
                'poster_url' => 'buzz_live.png',
                'category_id' => 3,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'All the buzzworthy content in one place, from live interviews to fun, energetic shows. 🎤⚡',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Tune IN',
                'poster_url' => 'tune_in.png',
                'category_id' => 4,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 3,
                'description' => 'Stay tuned to the latest live music performances and the freshest beats from top artists. 🎙️📻',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'DiscoverX',
                'poster_url' => 'discoverx.png',
                'category_id' => 5,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 4,
                'description' => 'Uncover the unknown with live explorations and educational content from around the globe. 🌍🔎',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'HeadlineX',
                'poster_url' => 'headlinex.png',
                'category_id' => 1,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Your go-to for breaking headlines and live updates, keeping you in the know. 🗞️🎯',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Xtreme Sports',
                'poster_url' => 'xtreme_sports.png',
                'category_id' => 2,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 2,
                'description' => 'Tune in for adrenaline-pumping sports events, from extreme sports to intense competition. 🏄‍♂️🔥',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Fun Box',
                'poster_url' => 'fun_box.png',
                'category_id' => 3,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'A playful mix of live comedy, gameshows, and entertainment to keep you laughing. 🤣📺',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Sound Wave',
                'poster_url' => 'sound_wave.png',
                'category_id' => 4,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 2,
                'description' => 'Feel the pulse of live music as you experience concerts and performances from the world’s best artists. 🎤🌊',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Learn LIVE',
                'poster_url' => 'learn_live.png',
                'category_id' => 5,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 4,
                'description' => 'Interactive educational programming, live lectures, and documentaries to spark your curiosity. 🎓📡',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Live Line',
                'poster_url' => 'live_line.png',
                'category_id' => 1,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Breaking news, live updates, and in-depth analysis at the speed of live broadcast. 📡⚡',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Pro Play',
                'poster_url' => 'pro_play.png',
                'category_id' => 2,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 3,
                'description' => 'Watch your favorite athletes and teams go head-to-head in thrilling live action. 🏅🎬',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Show MAX',
                'poster_url' => 'show_max.png',
                'category_id' => 3,
                'thumb_url' => NULL,
                'access' => 'paid',
                'plan_id' => 2,
                'description' => 'Maximize your entertainment with live shows, contests, and endless variety! 🎭💫',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'RhythmX',
                'poster_url' => 'rhythmx.png',
                'category_id' => 4,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Tune in for live performances, chart-topping hits, and music from around the world. 🎶🎧',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Insight TV',
                'poster_url' => 'insight_tv.png',
                'category_id' => 5,
                'thumb_url' => NULL,
                'access' => 'free',
                'plan_id' => NULL,
                'description' => 'Dive deep into thought-provoking live content that educates and inspires, from documentaries to expert talks. 📘🔍',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}