<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LiveTvStreamContentMappingTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('live_tv_stream_content_mapping')->delete();
        
        \DB::table('live_tv_stream_content_mapping')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tv_channel_id' => 1,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'tv_channel_id' => 2,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'tv_channel_id' => 3,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://abplivetv.akamaized.net/hls/live/2043010/hindi/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'tv_channel_id' => 4,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://d2q8p4pe5spbak.cloudfront.net/bpk-tv/9XM/9XM.isml/index.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'tv_channel_id' => 5,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://abplivetv.akamaized.net/hls/live/2043010/hindi/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'tv_channel_id' => 6,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://d2q8p4pe5spbak.cloudfront.net/bpk-tv/9XM/9XM.isml/index.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'tv_channel_id' => 7,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://abplivetv.akamaized.net/hls/live/2043010/hindi/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'tv_channel_id' => 8,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'tv_channel_id' => 9,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://d2q8p4pe5spbak.cloudfront.net/bpk-tv/9XM/9XM.isml/index.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'tv_channel_id' => 10,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://ndtv24x7elemarchana.akamaized.net/hls/live/2003678/ndtv24x7/ndtv24x7master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'tv_channel_id' => 11,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'tv_channel_id' => 12,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://d2q8p4pe5spbak.cloudfront.net/bpk-tv/9XM/9XM.isml/index.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'tv_channel_id' => 13,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://ndtv24x7elemarchana.akamaized.net/hls/live/2003678/ndtv24x7/ndtv24x7master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'tv_channel_id' => 14,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'tv_channel_id' => 15,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://abplivetv.akamaized.net/hls/live/2043010/hindi/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'tv_channel_id' => 16,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://d2q8p4pe5spbak.cloudfront.net/bpk-tv/9XM/9XM.isml/index.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'tv_channel_id' => 17,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://abplivetv.akamaized.net/hls/live/2043010/hindi/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'tv_channel_id' => 18,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'tv_channel_id' => 19,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://ndtv24x7elemarchana.akamaized.net/hls/live/2003678/ndtv24x7/ndtv24x7master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'tv_channel_id' => 20,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://d2q8p4pe5spbak.cloudfront.net/bpk-tv/9XM/9XM.isml/index.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'tv_channel_id' => 21,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'tv_channel_id' => 22,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://abplivetv.akamaized.net/hls/live/2043010/hindi/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'tv_channel_id' => 23,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'tv_channel_id' => 24,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://ndtv24x7elemarchana.akamaized.net/hls/live/2003678/ndtv24x7/ndtv24x7master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'tv_channel_id' => 25,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://d2q8p4pe5spbak.cloudfront.net/bpk-tv/9XM/9XM.isml/index.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'tv_channel_id' => 26,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'tv_channel_id' => 27,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://abplivetv.akamaized.net/hls/live/2043010/hindi/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'tv_channel_id' => 28,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://ndtv24x7elemarchana.akamaized.net/hls/live/2003678/ndtv24x7/ndtv24x7master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'tv_channel_id' => 29,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'tv_channel_id' => 30,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://d2q8p4pe5spbak.cloudfront.net/bpk-tv/9XM/9XM.isml/index.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'tv_channel_id' => 31,
                'type' => 't_url',
                'stream_type' => 'URL',
                'embedded' => NULL,
                'server_url' => 'https://abplivetv.akamaized.net/hls/live/2043010/hindi/master.m3u8',
                'server_url1' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-22 09:20:48',
                'updated_at' => '2024-10-22 09:20:48',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}