<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ReviewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('reviews')->delete();
        
        \DB::table('reviews')->insert(array (
            0 => 
            array (
                'id' => 1,
                'entertainment_id' => 8,
                'user_id' => 12,
                'rating' => 5,
                'review' => 'A gripping storyline with unexpected twists. Keeps you hooked till the very end. 🤯🔥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-07-29 09:20:42',
                'updated_at' => '2024-07-29 09:20:42',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'entertainment_id' => 5,
                'user_id' => 13,
                'rating' => 4,
                'review' => 'Amazing atmosphere and spooky vibes. Perfect for horror fans! 👁️🌑',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-04 09:20:42',
                'updated_at' => '2024-05-04 09:20:42',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'entertainment_id' => 14,
                'user_id' => 8,
                'rating' => 4,
                'review' => 'Keeps you guessing with every turn. The Monkey King\'s journey is riveting and intense. 🤯👀',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-29 09:20:42',
                'updated_at' => '2024-04-29 09:20:42',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'entertainment_id' => 8,
                'user_id' => 11,
                'rating' => 5,
                'review' => 'Non-stop action from start to finish! The fight scenes were incredible. 🎬💥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-02 09:20:42',
                'updated_at' => '2023-12-02 09:20:42',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'entertainment_id' => 2,
                'user_id' => 10,
                'rating' => 4,
                'review' => 'Absolutely loved the showdown scenes! The tension is palpable throughout. 🥳🎬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-27 09:20:42',
                'updated_at' => '2023-11-27 09:20:42',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'entertainment_id' => 13,
                'user_id' => 9,
                'rating' => 4,
                'review' => 'The cinematography and special effects are top-notch. A visual treat for action enthusiasts. 🌟🎥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-18 09:20:42',
                'updated_at' => '2024-10-18 09:20:42',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'entertainment_id' => 6,
                'user_id' => 14,
                'rating' => 5,
                'review' => 'Absolutely gripping from the first episode! The suspense is incredible. 🕵️‍♂️🔍',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-04 09:20:42',
                'updated_at' => '2024-05-04 09:20:42',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'entertainment_id' => 17,
                'user_id' => 7,
                'rating' => 4,
                'review' => 'Hilarious from start to finish! Couldn\'t stop laughing! 😂👏',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-18 09:20:42',
                'updated_at' => '2024-04-18 09:20:42',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'entertainment_id' => 6,
                'user_id' => 6,
                'rating' => 3,
                'review' => 'Brilliantly executed with superb acting. A must-watch for thriller fans. 🎭🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-17 09:20:42',
                'updated_at' => '2024-01-17 09:20:42',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'entertainment_id' => 7,
                'user_id' => 3,
                'rating' => 4,
                'review' => 'Fantastic choreography and intense combat sequences. Top-notch action film! 💪🎥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-30 09:20:42',
                'updated_at' => '2024-05-30 09:20:42',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'entertainment_id' => 4,
                'user_id' => 5,
                'rating' => 4,
                'review' => 'Each episode leaves you wanting more. The storyline is so gripping! 🎉🕶️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-16 09:20:42',
                'updated_at' => '2023-11-16 09:20:42',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'entertainment_id' => 1,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'Perfectly blends psychological horror with supernatural elements, keeping you on the edge of your seat and craving for more after each episode. 🔮😱',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-01 09:20:42',
                'updated_at' => '2023-11-01 09:20:42',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'entertainment_id' => 9,
                'user_id' => 9,
                'rating' => 5,
                'review' => 'A thrilling ride that keeps you hooked with its intense plot twists and stunning visuals. 🎬🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-05 09:20:42',
                'updated_at' => '2024-08-05 09:20:42',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'entertainment_id' => 10,
                'user_id' => 13,
                'rating' => 5,
                'review' => 'Loved the creativity and imagination in every scene. It\'s a delightful watch! 🌈✨',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-08 09:20:42',
                'updated_at' => '2024-01-08 09:20:42',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'entertainment_id' => 1,
                'user_id' => 3,
                'rating' => 4,
                'review' => 'A chilling series that grips you from the first scene to the last, leaving you haunted by its eerie atmosphere and suspenseful plot twists. 👻🌑',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-16 09:20:42',
                'updated_at' => '2024-04-16 09:20:42',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'entertainment_id' => 6,
                'user_id' => 5,
                'rating' => 4,
                'review' => 'The suspense is unbearable! Can’t wait for the next episode. 😬🚀',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-01 09:20:42',
                'updated_at' => '2024-02-01 09:20:42',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'entertainment_id' => 3,
                'user_id' => 8,
                'rating' => 5,
                'review' => 'My favorite show this season! The Guardian\'s Challenge episode was thrilling! 🛡️🚀',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-04 09:20:42',
                'updated_at' => '2024-03-04 09:20:42',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'entertainment_id' => 10,
                'user_id' => 3,
                'rating' => 4,
                'review' => 'A magical adventure with charming characters and beautiful animation! 🌼🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-08 09:20:42',
                'updated_at' => '2023-12-08 09:20:42',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'entertainment_id' => 8,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'Amazing cinematography and special effects! Truly a visual treat. 🎥✨',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-10 09:20:42',
                'updated_at' => '2024-08-10 09:20:42',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'entertainment_id' => 11,
                'user_id' => 10,
                'rating' => 4,
                'review' => 'Secrets of Zambezia delivers a powerful message with humor and adventure. 🌍😄',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-01 09:20:42',
                'updated_at' => '2024-10-01 09:20:42',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'entertainment_id' => 16,
                'user_id' => 5,
                'rating' => 4,
                'review' => 'Couldn\'t stop laughing! The antics of Tim and Tom are pure genius. 🤣🎉',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-03 09:20:42',
                'updated_at' => '2024-10-03 09:20:42',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'entertainment_id' => 7,
                'user_id' => 7,
                'rating' => 5,
                'review' => 'A thrilling ride with non-stop adrenaline! Couldn\'t take my eyes off the screen. 🚁🔥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-29 09:20:42',
                'updated_at' => '2024-03-29 09:20:42',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'entertainment_id' => 5,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'The suspense and horror elements are top-notch. Can\'t wait for more! 👻🔪',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-06 09:20:42',
                'updated_at' => '2024-10-06 09:20:42',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'entertainment_id' => 15,
                'user_id' => 8,
                'rating' => 5,
                'review' => 'Deep Sea Mysteries keeps you at the edge of your seat. Unveiling secrets of the deep has never been more thrilling! 🚢💀',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-05 09:20:42',
                'updated_at' => '2024-04-05 09:20:42',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'entertainment_id' => 9,
                'user_id' => 7,
                'rating' => 5,
                'review' => 'Loved the character development and the emotional depth. It\'s more than just action- it\'s a redemption story! 👍🎥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-17 09:20:42',
                'updated_at' => '2024-03-17 09:20:42',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'entertainment_id' => 5,
                'user_id' => 8,
                'rating' => 5,
                'review' => 'Each episode gets better and scarier. Highly recommend! 🕸️🕷️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-04 09:20:42',
                'updated_at' => '2024-10-04 09:20:42',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'entertainment_id' => 9,
                'user_id' => 14,
                'rating' => 3,
                'review' => 'The Gunfighter\'s Redemption is a true masterpiece of action cinema. It leaves you wanting more with its gripping storyline and epic showdowns. 🏆🌌',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-06-22 09:20:42',
                'updated_at' => '2024-06-22 09:20:42',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'entertainment_id' => 10,
                'user_id' => 4,
                'rating' => 3,
                'review' => 'Daizy\'s Enchanted Journey brings a smile to your face with its enchanting story. 🌸😄',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-13 09:20:42',
                'updated_at' => '2024-04-13 09:20:42',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'entertainment_id' => 6,
                'user_id' => 3,
                'rating' => 4,
                'review' => 'Twists and turns at every corner! Keeps you guessing until the end. 🤯🔎',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-19 09:20:42',
                'updated_at' => '2024-02-19 09:20:42',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'entertainment_id' => 2,
                'user_id' => 9,
                'rating' => 4,
                'review' => 'An intense start with plenty of action and a gripping storyline. Can\'t wait for more! 🤠🔥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-20 09:20:42',
                'updated_at' => '2024-02-20 09:20:42',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'entertainment_id' => 5,
                'user_id' => 3,
                'rating' => 3,
                'review' => 'A chilling start that kept me hooked from the first episode. So creepy! 😱🖤',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-02 09:20:42',
                'updated_at' => '2024-08-02 09:20:42',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'entertainment_id' => 9,
                'user_id' => 10,
                'rating' => 5,
                'review' => 'The Gunfighter\'s quest for redemption is both heart-wrenching and exhilarating. Captivating from the first shot to the last. 💔🔫',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-12 09:20:42',
                'updated_at' => '2024-04-12 09:20:42',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'entertainment_id' => 1,
                'user_id' => 5,
                'rating' => 4,
                'review' => 'An immersive journey into darkness where every shadow hides a secret, keeping you guessing and terrified until the very end. 🕯️😨',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-08 09:20:42',
                'updated_at' => '2024-01-08 09:20:42',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'entertainment_id' => 22,
                'user_id' => 14,
                'rating' => 5,
                'review' => 'Impressive cinematography and a storyline that keeps you hooked till the end. 🎥👌',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-30 09:20:42',
                'updated_at' => '2023-11-30 09:20:42',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'entertainment_id' => 14,
                'user_id' => 5,
                'rating' => 5,
                'review' => 'Gripping storyline with unexpected twists and heart-pounding action scenes! 🐒👑',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-25 09:20:42',
                'updated_at' => '2023-11-25 09:20:42',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'entertainment_id' => 13,
                'user_id' => 3,
                'rating' => 4,
                'review' => 'Loved the protagonist\'s charisma and the intense plot twists. Keeps you guessing! 🔥🕵️‍♂️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-18 09:20:42',
                'updated_at' => '2024-04-18 09:20:42',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'entertainment_id' => 6,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'The plot is so intricate and well-crafted. A real edge-of-your-seat thriller. 😲🔥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-03 09:20:42',
                'updated_at' => '2024-05-03 09:20:42',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'entertainment_id' => 2,
                'user_id' => 11,
                'rating' => 4,
                'review' => 'The characters are well-developed and the plot keeps you on the edge of your seat. 👍🕵️‍♂️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-19 09:20:42',
                'updated_at' => '2023-12-19 09:20:42',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'entertainment_id' => 3,
                'user_id' => 10,
                'rating' => 4,
                'review' => 'Raziel\'s journey is inspiring and beautifully animated. Can\'t wait for more! 🎉🦄',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-07 09:20:42',
                'updated_at' => '2024-08-07 09:20:42',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'entertainment_id' => 7,
                'user_id' => 9,
                'rating' => 3,
                'review' => 'Heart-pounding action with a hint of suspense. Action movie buffs will enjoy every moment. 🎞️👏',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-16 09:20:42',
                'updated_at' => '2024-08-16 09:20:42',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'entertainment_id' => 4,
                'user_id' => 12,
                'rating' => 4,
                'review' => 'The suspense in every episode keeps me hooked! Can\'t get enough of it. 🔍🎬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-07-07 09:20:42',
                'updated_at' => '2024-07-07 09:20:42',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'entertainment_id' => 10,
                'user_id' => 5,
                'rating' => 5,
                'review' => 'Perfect for family movie night - captivating and full of wonder! 🍿👪',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-04 09:20:42',
                'updated_at' => '2024-01-04 09:20:42',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'entertainment_id' => 5,
                'user_id' => 7,
                'rating' => 5,
                'review' => 'The storyline is gripping and the scares are genuine. Loving it! 🎃💀',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-16 09:20:42',
                'updated_at' => '2024-05-16 09:20:42',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'entertainment_id' => 12,
                'user_id' => 8,
                'rating' => 4,
                'review' => 'A visually stunning adventure that captivates from start to finish! 🎬🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-16 09:20:42',
                'updated_at' => '2024-01-16 09:20:42',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'entertainment_id' => 22,
                'user_id' => 11,
                'rating' => 5,
                'review' => 'Educational yet entertaining, perfect for history buffs and casual viewers alike. 📚📺',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-17 09:20:42',
                'updated_at' => '2024-05-17 09:20:42',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'entertainment_id' => 5,
                'user_id' => 6,
                'rating' => 4,
                'review' => 'Edge-of-your-seat horror with a captivating plot. So intense! 🥶🏚️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-05 09:20:42',
                'updated_at' => '2024-03-05 09:20:42',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'entertainment_id' => 8,
                'user_id' => 3,
                'rating' => 5,
                'review' => 'The characters were so well-developed, and the plot was intense. Loved every moment! 👍🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-21 09:20:42',
                'updated_at' => '2024-10-21 09:20:42',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'entertainment_id' => 6,
                'user_id' => 8,
                'rating' => 5,
                'review' => 'The characters are compelling, and the mystery deepens with each episode. 👏🕵️‍♀️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-20 09:20:42',
                'updated_at' => '2024-01-20 09:20:42',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'entertainment_id' => 11,
                'user_id' => 6,
                'rating' => 5,
                'review' => 'Loved the soundtrack! It perfectly complements the magical atmosphere of Zambezia. 🎵🎶',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-08 09:20:42',
                'updated_at' => '2024-04-08 09:20:42',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'entertainment_id' => 15,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'The ocean depths come alive with mystery and danger. Riveting from start to finish. 🌊🦑',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-06 09:20:42',
                'updated_at' => '2023-12-06 09:20:42',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'entertainment_id' => 6,
                'user_id' => 9,
                'rating' => 3,
                'review' => 'Each episode unveils more secrets and keeps you hooked. Fantastic storytelling! 📚🎬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-18 09:20:42',
                'updated_at' => '2024-03-18 09:20:42',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'entertainment_id' => 7,
                'user_id' => 6,
                'rating' => 4,
                'review' => 'Action-packed from start to finish! The stunts were mind-blowing. 🎬💥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-15 09:20:42',
                'updated_at' => '2023-12-15 09:20:42',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'entertainment_id' => 8,
                'user_id' => 13,
                'rating' => 5,
                'review' => 'The pacing was perfect, never a dull moment. Can\'t wait for a sequel! 🚀🎉',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-28 09:20:42',
                'updated_at' => '2023-12-28 09:20:42',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'entertainment_id' => 16,
                'user_id' => 14,
                'rating' => 3,
                'review' => 'Tim and Tom\'s chemistry is unbeatable. I wish there were more movies like this! 🌟👬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-06-08 09:20:42',
                'updated_at' => '2024-06-08 09:20:42',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'entertainment_id' => 9,
                'user_id' => 6,
                'rating' => 5,
                'review' => 'Action-packed and emotionally charged—this movie delivers on all fronts. A must-watch for action enthusiasts! 💥🎞️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-13 09:20:42',
                'updated_at' => '2024-10-13 09:20:42',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'entertainment_id' => 18,
                'user_id' => 11,
                'rating' => 4,
                'review' => 'I couldn\'t get enough of the comedic timing in this film. Pure comedy gold! ⏱️😄',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-11 09:20:42',
                'updated_at' => '2023-11-11 09:20:42',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'entertainment_id' => 8,
                'user_id' => 14,
                'rating' => 5,
                'review' => 'A thrilling ride with heart-pounding moments. Definitely recommend it to action fans! 🎢👏',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-03 09:20:42',
                'updated_at' => '2024-02-03 09:20:42',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'entertainment_id' => 11,
                'user_id' => 7,
                'rating' => 5,
                'review' => 'The storyline is engaging, and the characters are lovable. A must-watch animation! 🐦💖',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-09-29 09:20:42',
                'updated_at' => '2024-09-29 09:20:42',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'entertainment_id' => 5,
                'user_id' => 9,
                'rating' => 5,
                'review' => 'The acting and special effects are fantastic. Truly terrifying! 🌲🧟‍♀️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-12 09:20:42',
                'updated_at' => '2024-03-12 09:20:42',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'entertainment_id' => 12,
                'user_id' => 14,
                'rating' => 5,
                'review' => 'Clever humor and heartfelt moments make this a timeless classic. Highly recommend! 😄👏',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-26 09:20:42',
                'updated_at' => '2024-01-26 09:20:42',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'entertainment_id' => 22,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'The costumes and set designs transport you back in time. A visual feast! 🎨✨',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-22 09:20:42',
                'updated_at' => '2024-08-22 09:20:42',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'entertainment_id' => 9,
                'user_id' => 5,
                'rating' => 4,
                'review' => 'Gripping action from start to finish! The Gunfighter\'s journey is packed with adrenaline-pumping scenes. 🤠🔥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-09-21 09:20:42',
                'updated_at' => '2024-09-21 09:20:42',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'entertainment_id' => 26,
                'user_id' => 14,
                'rating' => 4,
                'review' => 'The scenery and music complement the story beautifully. It\'s a visual and emotional treat. 🎵🎥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-04 09:20:42',
                'updated_at' => '2024-03-04 09:20:42',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'entertainment_id' => 15,
                'user_id' => 11,
                'rating' => 4,
                'review' => 'Intriguing characters and a plot that sinks its hooks deep. Thrills and suspense galore! 👀🎥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-22 09:20:42',
                'updated_at' => '2023-12-22 09:20:42',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'entertainment_id' => 17,
                'user_id' => 6,
                'rating' => 5,
                'review' => 'Clever humor and witty dialogue make this a must-watch comedy! 🎭👍',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-19 09:20:42',
                'updated_at' => '2023-11-19 09:20:42',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'entertainment_id' => 13,
                'user_id' => 14,
                'rating' => 4,
                'review' => 'Gripping storyline with unexpected turns. I couldn\'t look away for a second! 🤯🔫',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-05 09:20:42',
                'updated_at' => '2024-04-05 09:20:42',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'entertainment_id' => 19,
                'user_id' => 11,
                'rating' => 5,
                'review' => 'Creepy atmosphere and unexpected twists make it a standout horror film. 🌑🕯️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-22 09:20:42',
                'updated_at' => '2023-12-22 09:20:42',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'entertainment_id' => 7,
                'user_id' => 8,
                'rating' => 3,
                'review' => 'Explosive scenes and gripping storyline. Kept me at the edge of my seat throughout. 🌟🔫',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-13 09:20:42',
                'updated_at' => '2024-02-13 09:20:42',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'entertainment_id' => 16,
                'user_id' => 10,
                'rating' => 4,
                'review' => 'A delightful comedy that had me giggling throughout. Tim and Tom are my new favorites! 🎈😁',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-09-21 09:20:42',
                'updated_at' => '2024-09-21 09:20:42',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'entertainment_id' => 7,
                'user_id' => 10,
                'rating' => 5,
                'review' => 'Loved the plot twists and the lead actor\'s performance. Definitely worth watching! 👍🎬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-03 09:20:42',
                'updated_at' => '2023-12-03 09:20:42',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'entertainment_id' => 11,
                'user_id' => 3,
                'rating' => 4,
                'review' => 'Captivating animation and a heartwarming storyline that keeps you engaged till the end. 🌟🎬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-30 09:20:42',
                'updated_at' => '2024-08-30 09:20:42',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'entertainment_id' => 16,
                'user_id' => 13,
                'rating' => 5,
                'review' => 'A feel-good movie with endless laughs. Perfect for a movie night with friends! 🍿😆',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-22 09:20:42',
                'updated_at' => '2024-05-22 09:20:42',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'entertainment_id' => 11,
                'user_id' => 11,
                'rating' => 5,
                'review' => 'Beautifully crafted characters and stunning visuals. A delight for all ages! 🦅🎨',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-26 09:20:42',
                'updated_at' => '2024-04-26 09:20:42',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'entertainment_id' => 23,
                'user_id' => 8,
                'rating' => 5,
                'review' => 'A feel-good film that leaves you motivated and optimistic. 🎥🌻',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-23 09:20:42',
                'updated_at' => '2024-05-23 09:20:42',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'entertainment_id' => 12,
                'user_id' => 12,
                'rating' => 5,
                'review' => 'The animation is top-notch, and the plot is both engaging and thought-provoking. 🎥🤔',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-23 09:20:42',
                'updated_at' => '2024-04-23 09:20:42',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'entertainment_id' => 13,
                'user_id' => 7,
                'rating' => 3,
                'review' => 'Perfect blend of action and suspense. It kept me at the edge of my seat throughout. 👏🎭',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-26 09:20:42',
                'updated_at' => '2024-03-26 09:20:42',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'entertainment_id' => 18,
                'user_id' => 14,
                'rating' => 4,
                'review' => 'Frank and Fearless bring laughter and charm to the screen. Thoroughly entertaining! 😂🎉',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-31 09:20:42',
                'updated_at' => '2023-12-31 09:20:42',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'entertainment_id' => 13,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'Action-packed from start to finish! The stunts and fight scenes are mind-blowing. 🎬💥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-02 09:20:42',
                'updated_at' => '2023-11-02 09:20:42',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'entertainment_id' => 17,
                'user_id' => 5,
                'rating' => 3,
                'review' => 'The cast nailed it! Each scene had me in stitches. 🤣🎬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-21 09:20:42',
                'updated_at' => '2024-10-21 09:20:42',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'entertainment_id' => 15,
                'user_id' => 12,
                'rating' => 5,
                'review' => 'Captivating storyline with chilling moments that leave you breathless. A must-watch for thriller enthusiasts! 😱🎬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-29 09:20:42',
                'updated_at' => '2023-12-29 09:20:42',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'entertainment_id' => 13,
                'user_id' => 13,
                'rating' => 4,
                'review' => 'Heart-pounding adrenaline rush! The Daring Player sets a new standard for action movies. 🚀👊',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-10-23 09:20:42',
                'updated_at' => '2023-10-23 09:20:42',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'entertainment_id' => 14,
                'user_id' => 11,
                'rating' => 5,
                'review' => 'Impressive cinematography and a plot that keeps you on the edge of your seat. Bravo! 🌟👏',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-23 09:20:42',
                'updated_at' => '2024-08-23 09:20:42',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'entertainment_id' => 19,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'A terrifying rollercoaster of fear and suspense. 🎢😨',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-07 09:20:42',
                'updated_at' => '2023-12-07 09:20:42',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'entertainment_id' => 21,
                'user_id' => 10,
                'rating' => 4,
                'review' => 'Engrossing narratives and stunning visuals make history come alive! 🎥✨',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-20 09:20:42',
                'updated_at' => '2024-05-20 09:20:42',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'entertainment_id' => 25,
                'user_id' => 13,
                'rating' => 5,
                'review' => 'I couldn\'t stop smiling throughout! A perfect feel-good movie for any day. 😊🎥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-03 09:20:42',
                'updated_at' => '2023-11-03 09:20:42',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'entertainment_id' => 14,
                'user_id' => 10,
                'rating' => 4,
                'review' => 'The suspense builds up perfectly. I couldn\'t take my eyes off the screen! 🎥🔍',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-15 09:20:42',
                'updated_at' => '2024-08-15 09:20:42',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'entertainment_id' => 1,
                'user_id' => 6,
                'rating' => 4,
                'review' => 'Masterfully crafted with spine-tingling moments that linger long after you\'ve finished watching. A must-watch for horror aficionados! 🎬👻',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-04 09:20:42',
                'updated_at' => '2024-02-04 09:20:42',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'entertainment_id' => 15,
                'user_id' => 3,
                'rating' => 5,
                'review' => 'Gripping plot twists and eerie underwater suspense! Keeps you guessing till the end. 🌊🔍',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-15 09:20:42',
                'updated_at' => '2023-11-15 09:20:42',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'entertainment_id' => 26,
                'user_id' => 5,
                'rating' => 4,
                'review' => 'A perfect movie for a cozy evening. It\'s romantic, emotional, and uplifting. 🍿🎬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-06-09 09:20:42',
                'updated_at' => '2024-06-09 09:20:42',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'entertainment_id' => 21,
                'user_id' => 13,
                'rating' => 5,
                'review' => 'Detailed and enlightening! It\'s like stepping back in time. 🕰️📜',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-06 09:20:42',
                'updated_at' => '2024-02-06 09:20:42',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'entertainment_id' => 19,
                'user_id' => 7,
                'rating' => 3,
                'review' => 'Hauntingly good! The suspense builds up perfectly. 🕰️🔦',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-19 09:20:42',
                'updated_at' => '2024-10-19 09:20:42',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'entertainment_id' => 16,
                'user_id' => 9,
                'rating' => 4,
                'review' => 'Hilarious from start to finish! Tim and Tom are comedy gold. 😂👌',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-11 09:20:42',
                'updated_at' => '2024-08-11 09:20:42',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'entertainment_id' => 24,
                'user_id' => 13,
                'rating' => 5,
                'review' => 'An emotional rollercoaster with a powerful message of perseverance. 🎢💫',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-19 09:20:42',
                'updated_at' => '2024-08-19 09:20:42',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'entertainment_id' => 23,
                'user_id' => 5,
                'rating' => 4,
                'review' => 'Rise Above is a testament to the human spirit\'s ability to overcome challenges. 🌠🙌',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-31 09:20:42',
                'updated_at' => '2024-01-31 09:20:42',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'entertainment_id' => 26,
                'user_id' => 12,
                'rating' => 5,
                'review' => 'This movie reminds us that love conquers all. It\'s a must-watch for romantics! 🌹💫',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-17 09:20:42',
                'updated_at' => '2024-10-17 09:20:42',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'entertainment_id' => 16,
                'user_id' => 6,
                'rating' => 5,
                'review' => 'Quirky and entertaining, this movie brightened my day. Highly recommend! 🌈❤️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-19 09:20:42',
                'updated_at' => '2024-08-19 09:20:42',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'entertainment_id' => 17,
                'user_id' => 3,
                'rating' => 5,
                'review' => 'Perfect pick-me-up comedy for any day of the week. 😄🎥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-13 09:20:42',
                'updated_at' => '2024-03-13 09:20:42',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'entertainment_id' => 15,
                'user_id' => 7,
                'rating' => 5,
                'review' => 'Atmospheric and hauntingly beautiful. Dive into this thriller for an unforgettable ride. 🌊🎞️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-30 09:20:42',
                'updated_at' => '2023-11-30 09:20:42',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'entertainment_id' => 17,
                'user_id' => 10,
                'rating' => 3,
                'review' => 'A feel-good comedy that delivers non-stop laughs. Highly recommend! 🌟🎉',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-05 09:20:42',
                'updated_at' => '2023-12-05 09:20:42',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'entertainment_id' => 24,
                'user_id' => 8,
                'rating' => 5,
                'review' => 'Inspirational from start to finish. It reminds us to never give up on our dreams. 🌟🎬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-30 09:20:42',
                'updated_at' => '2023-11-30 09:20:42',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'entertainment_id' => 18,
                'user_id' => 9,
                'rating' => 5,
                'review' => 'The chemistry between the characters is spot-on. Enjoyable and witty! 👏😆',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-20 09:20:42',
                'updated_at' => '2024-03-20 09:20:42',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'entertainment_id' => 21,
                'user_id' => 6,
                'rating' => 3,
                'review' => 'Each episode is a treasure trove of knowledge. Highly recommend for all ages! 🎓🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-09 09:20:42',
                'updated_at' => '2023-12-09 09:20:42',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'entertainment_id' => 23,
                'user_id' => 11,
                'rating' => 5,
                'review' => 'The performances are outstanding, making the message even more impactful. 👍🎭',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-31 09:20:42',
                'updated_at' => '2024-01-31 09:20:42',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'entertainment_id' => 26,
                'user_id' => 3,
                'rating' => 4,
                'review' => 'Such a heartwarming story! It\'s a beautiful journey of love and second chances. 💖😊',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-09-03 09:20:42',
                'updated_at' => '2024-09-03 09:20:42',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'entertainment_id' => 21,
                'user_id' => 7,
                'rating' => 5,
                'review' => 'A must-watch for history buffs! The storytelling is impeccable. 🤓🎬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-01 09:20:42',
                'updated_at' => '2024-02-01 09:20:42',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'entertainment_id' => 24,
                'user_id' => 6,
                'rating' => 5,
                'review' => 'A beautiful story of resilience and triumph against all odds. 🎥🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-27 09:20:42',
                'updated_at' => '2024-02-27 09:20:42',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'entertainment_id' => 20,
                'user_id' => 10,
                'rating' => 5,
                'review' => 'Perfect blend of suspense and horror. Hauntingly good! 👀🔪',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 09:20:42',
                'updated_at' => '2024-07-30 09:20:42',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'entertainment_id' => 26,
                'user_id' => 8,
                'rating' => 5,
                'review' => 'Forever in My Heart touched my soul. It\'s a timeless love story that stays with you. 💞📽️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-06-14 09:20:42',
                'updated_at' => '2024-06-14 09:20:42',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'entertainment_id' => 12,
                'user_id' => 13,
                'rating' => 4,
                'review' => 'An imaginative world that brings out the child in everyone. Loved every moment! 🌈👶',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-19 09:20:42',
                'updated_at' => '2024-10-19 09:20:42',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'entertainment_id' => 19,
                'user_id' => 6,
                'rating' => 4,
                'review' => 'Couldn\'t look away despite being scared out of my wits! 👀😳',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-02 09:20:42',
                'updated_at' => '2024-02-02 09:20:42',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'entertainment_id' => 18,
                'user_id' => 12,
                'rating' => 5,
                'review' => 'Clever writing and great performances make this movie a joy to watch. 📝🎥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-07 09:20:42',
                'updated_at' => '2024-01-07 09:20:42',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'entertainment_id' => 12,
                'user_id' => 3,
                'rating' => 4,
                'review' => 'The New Empire sets a new standard for animated movies. Truly magical! 🌠🎉',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-10-26 09:20:42',
                'updated_at' => '2023-10-26 09:20:42',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'entertainment_id' => 19,
                'user_id' => 9,
                'rating' => 5,
                'review' => 'Spine-chilling! Kept me awake all night. 😱👻',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-17 09:20:42',
                'updated_at' => '2024-04-17 09:20:42',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'entertainment_id' => 23,
                'user_id' => 9,
                'rating' => 5,
                'review' => 'This movie reminds us that anything is possible with determination and courage. 🌟💪',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-13 09:20:42',
                'updated_at' => '2024-05-13 09:20:42',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'entertainment_id' => 20,
                'user_id' => 5,
                'rating' => 5,
                'review' => 'Kept me on the edge of my seat the entire time! Terrifying twists and turns. 😱👻',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-15 09:20:42',
                'updated_at' => '2024-08-15 09:20:42',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'entertainment_id' => 25,
                'user_id' => 7,
                'rating' => 5,
                'review' => 'A timeless romance that sweeps you off your feet. Pure cinematic bliss! 🎬💞',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-07 09:20:42',
                'updated_at' => '2024-08-07 09:20:42',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'entertainment_id' => 21,
                'user_id' => 12,
                'rating' => 4,
                'review' => 'A fascinating exploration of ancient history, beautifully presented. 🌍🏛️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-07-01 09:20:42',
                'updated_at' => '2024-07-01 09:20:42',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'entertainment_id' => 20,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'The atmosphere was eerie, and the scares were genuinely frightening. Bravo! 🌑🎬',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-31 09:20:42',
                'updated_at' => '2024-01-31 09:20:42',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'entertainment_id' => 26,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'The chemistry between the leads is undeniable. I couldn\'t stop smiling throughout! 💑🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-06-09 09:20:42',
                'updated_at' => '2024-06-09 09:20:42',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'entertainment_id' => 22,
                'user_id' => 3,
                'rating' => 5,
                'review' => 'Captivating portrayal of ancient civilizations, rich in detail and authenticity. 🏛️📜',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-04 09:20:42',
                'updated_at' => '2024-02-04 09:20:42',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'entertainment_id' => 23,
                'user_id' => 3,
                'rating' => 5,
                'review' => 'Rise Above delivers a powerful message of perseverance and resilience. 🌈👏',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-17 09:20:42',
                'updated_at' => '2024-05-17 09:20:42',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'entertainment_id' => 22,
                'user_id' => 8,
                'rating' => 5,
                'review' => 'A fascinating journey through history, beautifully depicted with stellar performances. 🎭🌍',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-21 09:20:42',
                'updated_at' => '2023-12-21 09:20:42',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'entertainment_id' => 24,
                'user_id' => 12,
                'rating' => 3,
                'review' => 'Touching and motivational. It\'s a journey everyone should experience. 🚀😊',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-29 09:20:42',
                'updated_at' => '2024-04-29 09:20:42',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'entertainment_id' => 23,
                'user_id' => 14,
                'rating' => 3,
                'review' => 'A deeply inspiring movie that touches the heart and uplifts the spirit. 🌟😊',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-09-23 09:20:42',
                'updated_at' => '2024-09-23 09:20:42',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'entertainment_id' => 22,
                'user_id' => 9,
                'rating' => 5,
                'review' => 'Engrossing narrative that brings the past to life with every scene. 🕰️🔍',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-07-15 09:20:42',
                'updated_at' => '2024-07-15 09:20:42',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'entertainment_id' => 23,
                'user_id' => 4,
                'rating' => 3,
                'review' => 'The storyline is moving, and the characters\' journeys are truly inspirational. 🎬❤️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-06-28 09:20:42',
                'updated_at' => '2024-06-28 09:20:42',
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'entertainment_id' => 25,
                'user_id' => 6,
                'rating' => 3,
                'review' => 'Heartwarming and beautifully romantic, a love story that stays with you forever. 💖🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-10-28 09:20:42',
                'updated_at' => '2023-10-28 09:20:42',
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'entertainment_id' => 24,
                'user_id' => 3,
                'rating' => 4,
                'review' => 'This movie inspired me deeply. A powerful reminder of the strength within us all. 🌟🙌',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-14 09:20:42',
                'updated_at' => '2024-03-14 09:20:42',
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'entertainment_id' => 20,
                'user_id' => 12,
                'rating' => 4,
                'review' => 'Creepy and atmospheric. It\'s a horror fan\'s dream come true! 🌌🏚️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-29 09:20:42',
                'updated_at' => '2024-08-29 09:20:42',
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'entertainment_id' => 21,
                'user_id' => 3,
                'rating' => 5,
                'review' => 'An epic journey through the origins of civilization. Educational and captivating! 📚🌅',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-15 09:20:42',
                'updated_at' => '2024-03-15 09:20:42',
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'entertainment_id' => 25,
                'user_id' => 3,
                'rating' => 5,
                'review' => 'This movie made me believe in love all over again. Simply breathtaking! 💕😍',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-03-02 09:20:42',
                'updated_at' => '2024-03-02 09:20:42',
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'entertainment_id' => 20,
                'user_id' => 8,
                'rating' => 4,
                'review' => 'A bone-chilling experience that left me checking over my shoulder. Highly recommend! 🕯️👁️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-10-30 09:20:42',
                'updated_at' => '2023-10-30 09:20:42',
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'entertainment_id' => 10,
                'user_id' => 12,
                'rating' => 5,
                'review' => 'Daizy\'s journey is heartwarming and filled with lessons for all ages. 🎈😊',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-15 09:20:42',
                'updated_at' => '2024-05-15 09:20:42',
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'entertainment_id' => 24,
                'user_id' => 7,
                'rating' => 5,
                'review' => 'The characters\' journeys are incredibly moving. You\'ll laugh, cry, and feel inspired. 💖😭',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-07-21 09:20:42',
                'updated_at' => '2024-07-21 09:20:42',
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'entertainment_id' => 19,
                'user_id' => 14,
                'rating' => 4,
                'review' => 'Every shadow feels like it\'s watching you. Thrilling till the end! 🌌👁️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-07-01 09:20:42',
                'updated_at' => '2024-07-01 09:20:42',
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'entertainment_id' => 1,
                'user_id' => 7,
                'rating' => 5,
                'review' => 'Evokes a sense of dread and excitement simultaneously, offering a thrilling rollercoaster ride through fear and suspense. 🎢😱',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-06-12 09:20:42',
                'updated_at' => '2024-06-12 09:20:42',
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'entertainment_id' => 2,
                'user_id' => 12,
                'rating' => 4,
                'review' => 'Fantastic cinematography and thrilling gunfights! A must-watch for Western fans. 📽️🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-05 09:20:42',
                'updated_at' => '2024-05-05 09:20:42',
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'entertainment_id' => 22,
                'user_id' => 5,
                'rating' => 5,
                'review' => 'Each moment feels like a glimpse into a forgotten era. Absolutely mesmerizing! 🌌🔮',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-01 09:20:42',
                'updated_at' => '2024-10-01 09:20:42',
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'entertainment_id' => 2,
                'user_id' => 13,
                'rating' => 5,
                'review' => 'Each episode is better than the last. The story is captivating and full of surprises. 🎉🚀',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-31 09:20:42',
                'updated_at' => '2023-12-31 09:20:42',
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'entertainment_id' => 5,
                'user_id' => 12,
                'rating' => 4,
                'review' => 'The twists and turns are brilliant. A must-watch for horror lovers! 🌫️📺',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-17 09:20:42',
                'updated_at' => '2023-12-17 09:20:42',
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'entertainment_id' => 4,
                'user_id' => 13,
                'rating' => 5,
                'review' => 'Edge-of-your-seat excitement and unexpected twists. Absolutely thrilling! 😱🚀',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-09 09:20:42',
                'updated_at' => '2023-12-09 09:20:42',
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'entertainment_id' => 10,
                'user_id' => 7,
                'rating' => 5,
                'review' => 'The animation is top-notch, and the story keeps you hooked from start to finish. 🎬💖',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-26 09:20:42',
                'updated_at' => '2024-08-26 09:20:42',
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'entertainment_id' => 20,
                'user_id' => 3,
                'rating' => 5,
                'review' => 'Gripping from start to finish. The tension builds up beautifully. 🎢💀',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-09 09:20:42',
                'updated_at' => '2024-04-09 09:20:42',
                'deleted_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'entertainment_id' => 25,
                'user_id' => 12,
                'rating' => 5,
                'review' => 'Touching and emotional, it captures the essence of true love\'s journey. 🌹😢',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-10-26 09:20:42',
                'updated_at' => '2023-10-26 09:20:42',
                'deleted_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'entertainment_id' => 1,
                'user_id' => 8,
                'rating' => 5,
                'review' => 'Captivating and spine-chilling, with a narrative that grips your imagination and leaves you pondering its mysteries. 🔍🌑',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-07-10 09:20:42',
                'updated_at' => '2024-07-10 09:20:42',
                'deleted_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'entertainment_id' => 4,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'Great character development and intense scenes. A top-notch thriller! 👏🔥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-04-27 09:20:42',
                'updated_at' => '2024-04-27 09:20:42',
                'deleted_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'entertainment_id' => 2,
                'user_id' => 14,
                'rating' => 5,
                'review' => 'The perfect blend of drama and action. The Gunslinger is a true hero! 👏🏜️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-14 09:20:42',
                'updated_at' => '2024-01-14 09:20:42',
                'deleted_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'entertainment_id' => 11,
                'user_id' => 9,
                'rating' => 4,
                'review' => 'An enchanting journey that sparks imagination and leaves you wanting more. ✨🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-07-01 09:20:42',
                'updated_at' => '2024-07-01 09:20:42',
                'deleted_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'entertainment_id' => 3,
                'user_id' => 9,
                'rating' => 5,
                'review' => 'The animation is stunning, and the story is captivating. Love Raziel\'s bravery! 🐉🎨',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-07-13 09:20:42',
                'updated_at' => '2024-07-13 09:20:42',
                'deleted_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'entertainment_id' => 26,
                'user_id' => 10,
                'rating' => 3,
                'review' => 'I cried happy tears! This movie reaffirms the power of love and hope. 💖😊',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-10-08 09:20:42',
                'updated_at' => '2024-10-08 09:20:42',
                'deleted_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'entertainment_id' => 3,
                'user_id' => 3,
                'rating' => 5,
                'review' => 'A magical adventure that kept my kids and me glued to the screen! 🌲✨',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-09-30 09:20:42',
                'updated_at' => '2024-09-30 09:20:42',
                'deleted_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'entertainment_id' => 14,
                'user_id' => 12,
                'rating' => 4,
                'review' => 'A must-watch for thriller enthusiasts. The Monkey King\'s quest will leave you wanting more. 🎭🌌',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-06-20 09:20:42',
                'updated_at' => '2024-06-20 09:20:42',
                'deleted_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'entertainment_id' => 18,
                'user_id' => 3,
                'rating' => 5,
                'review' => 'A comedy that hits all the right notes. Fun, light-hearted, and highly enjoyable! 🎶😊',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-01-25 09:20:42',
                'updated_at' => '2024-01-25 09:20:42',
                'deleted_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'entertainment_id' => 16,
                'user_id' => 6,
                'rating' => 5,
                'review' => 'The cinematography is fantastic, and the suspense never lets up. Highly recommend! 🎥🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-25 09:20:42',
                'updated_at' => '2024-08-25 09:20:42',
                'deleted_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'entertainment_id' => 21,
                'user_id' => 8,
                'rating' => 4,
                'review' => 'The scale and depth of this series are truly impressive. History enthusiasts will be hooked! 🌐🔍',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-05 09:20:42',
                'updated_at' => '2024-08-05 09:20:42',
                'deleted_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'entertainment_id' => 13,
                'user_id' => 11,
                'rating' => 5,
                'review' => 'Perfect mix of fantasy and adventure. The Final Showdown was epic! ⚔️🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-09 09:20:42',
                'updated_at' => '2024-05-09 09:20:42',
                'deleted_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'entertainment_id' => 19,
                'user_id' => 13,
                'rating' => 4,
                'review' => 'Heart-pounding moments that will linger long after the credits roll. Must-watch for horror enthusiasts! 🎥👹',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-12 09:20:42',
                'updated_at' => '2024-08-12 09:20:42',
                'deleted_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'entertainment_id' => 14,
                'user_id' => 6,
                'rating' => 4,
                'review' => 'Intriguing characters and stunning visual effects. A thrilling ride from start to finish. 🎬🔥',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-09-25 09:20:42',
                'updated_at' => '2024-09-25 09:20:42',
                'deleted_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'entertainment_id' => 12,
                'user_id' => 5,
                'rating' => 5,
                'review' => 'Heartwarming story with lovable characters. Perfect for family movie night! 🍿❤️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-03 09:20:42',
                'updated_at' => '2024-02-03 09:20:42',
                'deleted_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'entertainment_id' => 19,
                'user_id' => 3,
                'rating' => 4,
                'review' => 'Gripping horror that leaves you checking the shadows. Not for the faint-hearted! 🚪🌚',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-02-28 09:20:42',
                'updated_at' => '2024-02-28 09:20:42',
                'deleted_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'entertainment_id' => 18,
                'user_id' => 4,
                'rating' => 5,
                'review' => 'A comedic adventure that keeps you smiling from start to finish. 😄🌟',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-11-25 09:20:43',
                'updated_at' => '2023-11-25 09:20:43',
                'deleted_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'entertainment_id' => 13,
                'user_id' => 7,
                'rating' => 5,
                'review' => 'The Hidden Fortress episode was full of unexpected twists and turns! So exciting! 🏰🔍',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-08-25 09:20:43',
                'updated_at' => '2024-08-25 09:20:43',
                'deleted_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'entertainment_id' => 17,
                'user_id' => 9,
                'rating' => 5,
                'review' => 'The plot is brilliantly crafted with a perfect mix of mystery and action. 📺🕵️‍♂️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-06-10 09:20:43',
                'updated_at' => '2024-06-10 09:20:43',
                'deleted_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'entertainment_id' => 24,
                'user_id' => 4,
                'rating' => 4,
                'review' => 'Couldn\'t help but smile throughout. Pure comedy gold! 😊👌',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-09-12 09:20:43',
                'updated_at' => '2024-09-12 09:20:43',
                'deleted_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'entertainment_id' => 9,
                'user_id' => 14,
                'rating' => 5,
                'review' => 'A masterful blend of intrigue and drama. Every scene is filled with tension. 😱🏙️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-21 09:20:44',
                'updated_at' => '2023-12-21 09:20:44',
                'deleted_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'entertainment_id' => 12,
                'user_id' => 11,
                'rating' => 4,
                'review' => 'Forever and a Day is a masterpiece in romantic storytelling. A must-watch! 🌈❤️',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2023-12-07 09:20:45',
                'updated_at' => '2023-12-07 09:20:45',
                'deleted_at' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'entertainment_id' => 7,
                'user_id' => 10,
                'rating' => 4,
                'review' => 'Heartfelt and uplifting. It leaves you with a sense of hope and determination. 🌈💪',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-07-14 09:20:45',
                'updated_at' => '2024-07-14 09:20:45',
                'deleted_at' => NULL,
            ),
            167 => 
            array (
                'id' => 168,
                'entertainment_id' => 12,
                'user_id' => 5,
                'rating' => 5,
                'review' => 'The chemistry between the leads is magical. It\'s a love story you won\'t forget. ✨👫',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-20 09:20:45',
                'updated_at' => '2024-05-20 09:20:45',
                'deleted_at' => NULL,
            ),
            168 => 
            array (
                'id' => 169,
                'entertainment_id' => 18,
                'user_id' => 8,
                'rating' => 4,
                'review' => 'Loved the quirky humor and unexpected twists. A must-watch for comedy lovers. 🎬🤩',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-13 09:20:45',
                'updated_at' => '2024-05-13 09:20:45',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}