<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'username' => NULL,
                'first_name' => 'Super',
                'last_name' => 'Admin',
                'email' => 'admin@streamit.com',
                'mobile' => '+12123567890',
                'login_type' => NULL,
                'file_url' => 'super_admin.png',
                'gender' => 'female',
                'date_of_birth' => '1996-01-29',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$Oz6Cqw.2MEdnplHhrXo/9efn2BoeFOj6ZLV3BqeL0z4e0pMS5pPom',
                'is_banned' => 0,
                'is_subscribe' => 0,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => NULL,
                'user_type' => 'admin',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'username' => NULL,
                'first_name' => 'Ivan',
                'last_name' => 'Norris',
                'email' => 'demo@streamit.com',
                'mobile' => '+12124567899',
                'login_type' => NULL,
                'file_url' => 'demo_admin.png',
                'gender' => 'male',
                'date_of_birth' => '1988-07-29',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$8N.y1f56bs4BoeAyov1ZaOmQIaOcAzKpz8I2A9lUfvweBa1/7QKfC',
                'is_banned' => 0,
                'is_subscribe' => 0,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => NULL,
                'user_type' => 'demo_admin',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'username' => NULL,
                'first_name' => 'John',
                'last_name' => 'Doe',
                'email' => 'john@gmail.com',
                'mobile' => '+911234567890',
                'login_type' => 'otp',
                'file_url' => 'john.png',
                'gender' => 'male',
                'date_of_birth' => '1990-02-13',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$hIvHTlpYnBVxMWo3Vk8CIe7dDU4FBaqjk3zTzYmknGH2i/lj7v3Wm',
                'is_banned' => 0,
                'is_subscribe' => 1,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '101 Pine Lane Miami, FL 33101 United States',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'username' => NULL,
                'first_name' => 'Tristan',
                'last_name' => 'Erickson',
                'email' => 'tristan@gmail.com',
                'mobile' => '+447911123456',
                'login_type' => 'otp',
                'file_url' => 'tristan.png',
                'gender' => 'male',
                'date_of_birth' => '1992-05-21',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$weZlQ7Qbt3u2Cng1PwbL1.GECEgOyoMOIZZbunLmveE75oxzu0Kgq',
                'is_banned' => 0,
                'is_subscribe' => 1,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '46 Oxford Road London, W1D 1BS United Kingdom',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'username' => NULL,
                'first_name' => 'Felix',
                'last_name' => 'Harris',
                'email' => 'felix@gmail.com',
                'mobile' => '+12124567890',
                'login_type' => 'otp',
                'file_url' => 'felix.png',
                'gender' => 'male',
                'date_of_birth' => '1996-02-02',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$2jVs1zxy4vHVXlWwqmoRtuOhgj9l4E2qCnEFzOlFnilBt6wWfIIWW',
                'is_banned' => 0,
                'is_subscribe' => 1,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '3 Queen Street Sydney, NSW 2000 Australia',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'username' => NULL,
                'first_name' => 'Harry',
                'last_name' => 'Victoria',
                'email' => 'harry@gmail.com',
                'mobile' => '+447911123456',
                'login_type' => 'otp',
                'file_url' => 'harry.png',
                'gender' => 'male',
                'date_of_birth' => '1987-07-08',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$USerTu5ezgfx3.pasAtfmu832oTBKrOgwSvbsgQMDwIznicGyjKlK',
                'is_banned' => 0,
                'is_subscribe' => 1,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '11 Rue de Rivoli Paris, 75001 France',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'username' => NULL,
                'first_name' => 'Jorge',
                'last_name' => 'Perez',
                'email' => 'jorge@gmail.com',
                'mobile' => '+496912345678',
                'login_type' => 'otp',
                'file_url' => 'jorge.png',
                'gender' => 'male',
                'date_of_birth' => '1991-01-01',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$6Z1EesCFxZTAWRmrNxkwsek8WwAOAHHbzfwacLLL7OiQWnOZX3ZjS',
                'is_banned' => 0,
                'is_subscribe' => 0,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '20 Kurfürstendamm Berlin, 10719 Germany',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'username' => NULL,
                'first_name' => 'Joy',
                'last_name' => 'Hanry',
                'email' => 'joy@gmail.com',
                'mobile' => '+81312345678',
                'login_type' => 'otp',
                'file_url' => 'joy.png',
                'gender' => 'male',
                'date_of_birth' => '1993-07-10',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$RsgY0QFCcqB8d5nVWeiNyulpqpFuV6QwryhfwBH6SUPe5fwqj7PmC',
                'is_banned' => 0,
                'is_subscribe' => 1,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '3 Shibuya Street Tokyo, 150-0002 Japan',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'username' => NULL,
                'first_name' => 'Deborah',
                'last_name' => 'Thomas',
                'email' => 'deborah@gmail.com',
                'mobile' => '+81312355678',
                'login_type' => 'otp',
                'file_url' => 'deborah.png',
                'gender' => 'female',
                'date_of_birth' => '1992-03-26',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$3cs2pjtwKrENBtMdccjSg.gi6uCBNzO1qnb7EGegDAMujI1Pt1sZq',
                'is_banned' => 0,
                'is_subscribe' => 1,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '7 Maple Avenue Toronto, ON M5H 2N2 Canada',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'username' => NULL,
                'first_name' => 'Katie',
                'last_name' => 'Brown',
                'email' => 'katie@gmail.com',
                'mobile' => '+12124467890',
                'login_type' => 'otp',
                'file_url' => 'katie.png',
                'gender' => 'female',
                'date_of_birth' => '1994-08-16',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$cugYcSc4evnq0qk.6Ji3p.SK0mmvNjZpCajYYNUeU.YqlledbzLGS',
                'is_banned' => 0,
                'is_subscribe' => 1,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '14 Gran Vía Madrid, 28013 Spain',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'username' => NULL,
                'first_name' => 'Dorothy',
                'last_name' => 'Erickson',
                'email' => 'dorothy@gmail.com',
                'mobile' => '+12124577890',
                'login_type' => 'otp',
                'file_url' => 'dorothy.png',
                'gender' => 'female',
                'date_of_birth' => '1989-10-10',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$50NxkVPj9ctSbHNp2S/FvuYubZhVE.eSIBEBf487GkGFU6dUwCLqC',
                'is_banned' => 0,
                'is_subscribe' => 0,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '50 Paulista Avenue São Paulo, SP 01310-100 Brazil',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'username' => NULL,
                'first_name' => 'Lisa',
                'last_name' => 'Lucas',
                'email' => 'lisa@gmail.com',
                'mobile' => '+12124567790',
                'login_type' => 'otp',
                'file_url' => 'lisa.png',
                'gender' => 'female',
                'date_of_birth' => '1993-08-03',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$Ki5A16p44Lpo9ziVzD9cF.kVxjQ/nNTsweOZ39P0WLl5o2XrzUY0i',
                'is_banned' => 0,
                'is_subscribe' => 0,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '6 Sheikh Zayed Road Dubai, 00000 United Arab Emirates',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'username' => NULL,
                'first_name' => 'Tracy',
                'last_name' => 'Jones',
                'email' => 'tracy@gmail.com',
                'mobile' => '+913465656789',
                'login_type' => 'otp',
                'file_url' => 'tracy.png',
                'gender' => 'female',
                'date_of_birth' => '1990-11-19',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$ALxbWl3XNOJf.IKIth3bYOJ2N1G/5FIBTmjm/wCOG0n.Wndbv4Qea',
                'is_banned' => 0,
                'is_subscribe' => 0,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '71 Orchard Road Singapore, 238838 Singapore',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'username' => NULL,
                'first_name' => 'Stella',
                'last_name' => 'Green',
                'email' => 'stella@gmail.com',
                'mobile' => '+913465756789',
                'login_type' => 'otp',
                'file_url' => 'stella.png',
                'gender' => 'female',
                'date_of_birth' => '1991-12-18',
                'email_verified_at' => '2024-10-22 09:19:56',
                'password' => '$2y$10$fMM6iBbieMN0YywCzRKU3OInUb2h5jv0kEJqTZiZVjKRZaE5xq9GS',
                'is_banned' => 0,
                'is_subscribe' => 1,
                'status' => 1,
                'last_notification_seen' => NULL,
                'address' => '15 Redwood Way Phoenix, AZ 85001 United States',
                'user_type' => 'user',
                'remember_token' => NULL,
                'created_at' => '2024-10-22 09:19:56',
                'updated_at' => '2024-10-22 09:19:57',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}