<?php

namespace Modules\Currency\database\seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencyDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        \DB::table('currencies')->delete();

        \DB::table('currencies')->insert(array (
            0 =>
            array (
                'id' => 1,
                'currency_name' => 'United States Dollar',
                'currency_symbol' => '$',
                'currency_code' => 'USD',
                'is_primary' => 1,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:18:52',
                'updated_at' => '2024-07-30 07:19:18',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'currency_code' => 'EUR',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:19:08',
                'updated_at' => '2024-07-30 07:19:08',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'currency_name' => 'Indian Rupee',
                'currency_symbol' => '₹',
                'currency_code' => 'INR',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:19:52',
                'updated_at' => '2024-07-30 07:19:52',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'currency_name' => 'Brazilian Real',
                'currency_symbol' => 'R$',
                'currency_code' => 'BRL',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => '.',
                'decimal_separator' => ',',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:20:00',
                'updated_at' => '2024-07-30 07:20:00',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'currency_name' => 'British Pound',
                'currency_symbol' => '£',
                'currency_code' => 'GBP',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:20:10',
                'updated_at' => '2024-07-30 07:20:10',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'currency_name' => 'Japanese Yen',
                'currency_symbol' => '¥',
                'currency_code' => 'JPY',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 0,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:20:20',
                'updated_at' => '2024-07-30 07:20:20',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'currency_name' => 'Canadian Dollar',
                'currency_symbol' => 'C$',
                'currency_code' => 'CAD',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:20:30',
                'updated_at' => '2024-07-30 07:20:30',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'currency_name' => 'Australian Dollar',
                'currency_symbol' => 'A$',
                'currency_code' => 'AUD',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:20:40',
                'updated_at' => '2024-07-30 07:20:40',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'currency_name' => 'Swiss Franc',
                'currency_symbol' => 'CHF',
                'currency_code' => 'CHF',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => "'",
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:20:50',
                'updated_at' => '2024-07-30 07:20:50',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'currency_name' => 'Chinese Yuan',
                'currency_symbol' => '¥',
                'currency_code' => 'CNY',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:21:00',
                'updated_at' => '2024-07-30 07:21:00',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'currency_name' => 'Mexican Peso',
                'currency_symbol' => '$',
                'currency_code' => 'MXN',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:21:10',
                'updated_at' => '2024-07-30 07:21:10',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'currency_name' => 'Singapore Dollar',
                'currency_symbol' => 'S$',
                'currency_code' => 'SGD',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:21:20',
                'updated_at' => '2024-07-30 07:21:20',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'currency_name' => 'Hong Kong Dollar',
                'currency_symbol' => 'HK$',
                'currency_code' => 'HKD',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:21:30',
                'updated_at' => '2024-07-30 07:21:30',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'currency_name' => 'New Zealand Dollar',
                'currency_symbol' => 'NZ$',
                'currency_code' => 'NZD',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:21:40',
                'updated_at' => '2024-07-30 07:21:40',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'currency_name' => 'Swedish Krona',
                'currency_symbol' => 'kr',
                'currency_code' => 'SEK',
                'is_primary' => 0,
                'currency_position' => 'right',
                'no_of_decimal' => 2,
                'thousand_separator' => ' ',
                'decimal_separator' => ',',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:21:50',
                'updated_at' => '2024-07-30 07:21:50',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'currency_name' => 'Norwegian Krone',
                'currency_symbol' => 'kr',
                'currency_code' => 'NOK',
                'is_primary' => 0,
                'currency_position' => 'right',
                'no_of_decimal' => 2,
                'thousand_separator' => ' ',
                'decimal_separator' => ',',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:22:00',
                'updated_at' => '2024-07-30 07:22:00',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'currency_name' => 'Danish Krone',
                'currency_symbol' => 'kr',
                'currency_code' => 'DKK',
                'is_primary' => 0,
                'currency_position' => 'right',
                'no_of_decimal' => 2,
                'thousand_separator' => ' ',
                'decimal_separator' => ',',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:22:10',
                'updated_at' => '2024-07-30 07:22:10',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'currency_name' => 'Polish Zloty',
                'currency_symbol' => 'zł',
                'currency_code' => 'PLN',
                'is_primary' => 0,
                'currency_position' => 'right',
                'no_of_decimal' => 2,
                'thousand_separator' => ' ',
                'decimal_separator' => ',',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:22:20',
                'updated_at' => '2024-07-30 07:22:20',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'currency_name' => 'Czech Koruna',
                'currency_symbol' => 'Kč',
                'currency_code' => 'CZK',
                'is_primary' => 0,
                'currency_position' => 'right',
                'no_of_decimal' => 2,
                'thousand_separator' => ' ',
                'decimal_separator' => ',',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:22:30',
                'updated_at' => '2024-07-30 07:22:30',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'currency_name' => 'Thai Baht',
                'currency_symbol' => '฿',
                'currency_code' => 'THB',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:22:40',
                'updated_at' => '2024-07-30 07:22:40',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'currency_name' => 'Malaysian Ringgit',
                'currency_symbol' => 'RM',
                'currency_code' => 'MYR',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:22:50',
                'updated_at' => '2024-07-30 07:22:50',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'currency_name' => 'Philippine Peso',
                'currency_symbol' => '₱',
                'currency_code' => 'PHP',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:23:00',
                'updated_at' => '2024-07-30 07:23:00',
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'currency_name' => 'Israeli Shekel',
                'currency_symbol' => '₪',
                'currency_code' => 'ILS',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ',',
                'decimal_separator' => '.',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:23:10',
                'updated_at' => '2024-07-30 07:23:10',
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'currency_name' => 'South African Rand',
                'currency_symbol' => 'R',
                'currency_code' => 'ZAR',
                'is_primary' => 0,
                'currency_position' => 'left',
                'no_of_decimal' => 2,
                'thousand_separator' => ' ',
                'decimal_separator' => ',',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2024-07-30 07:23:20',
                'updated_at' => '2024-07-30 07:23:20',
                'deleted_at' => NULL,
            ),
        ));
    }
}
